from turtle import Turtle, Screen
timmy = Turtle()
timmy.shape("turtle")
timmy.pencolor("chartreuse3")
my_screen = Screen()
timmy.forward(100)
timmy.left(90)
timmy.forward(100)
timmy.left(90)
timmy.forward(100)
timmy.left(90)
timmy.forward(100)

timmy.forward(100)
timmy.left(120)
timmy.forward(100)
timmy.left(120)
timmy.forward(100)
my_screen.exitonclick()
